version: '3.5'

services:
   webapp-service:
      container_name: 'webapp-service'
      build:
        context: .
        dockerfile: ./Dockerfile

      volumes:
        - ./webapp/:/usr/DocumentLibrary/webapp/
      command: "python -u restapp/main.py"
      stdin_open: true

      ports:
        - "9876:9876"